[package]
name = "cells_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cell_family"
path = "src/cell_family.rs"

[dependencies]
cell-family = "0.1.0"
